import { Category, Product } from './types'

export const mockCategories: Category[] = [
  { id: '1', name: 'Fish', slug: 'fish', description: 'Fresh fish options', order: 1 },
  { id: '2', name: 'Chips', slug: 'chips', description: 'Classic chips', order: 2 },
  { id: '3', name: 'Drinks', slug: 'drinks', description: 'Refreshing beverages', order: 3 },
  { id: '4', name: 'Family Deals', slug: 'family-deals', description: 'Value family meals', order: 4 },
  { id: '5', name: 'Special Offers', slug: 'special-offers', description: 'Limited time offers', order: 5 },
]

export const mockProducts: Product[] = [
  // Fish
  {
    id: '1',
    name: 'Classic Cod & Chips',
    description: 'Fresh Atlantic cod served with crispy golden chips',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=400&h=300&fit=crop',
    categorySlug: 'fish',
    categoryId: '1',
    inStock: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Haddock & Chips',
    description: 'Sustainable haddock with hand-cut chips',
    price: 13.49,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    categorySlug: 'fish',
    categoryId: '1',
    inStock: true,
    featured: true,
  },
  {
    id: '3',
    name: 'Fish Burger',
    description: 'Crispy fish fillet with fresh lettuce and tartar sauce',
    price: 9.99,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    categorySlug: 'fish',
    categoryId: '1',
    inStock: true,
    featured: false,
  },
  // Chips
  {
    id: '4',
    name: 'Regular Chips',
    description: 'Classic hand-cut chips with sea salt',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop',
    categorySlug: 'chips',
    categoryId: '2',
    inStock: true,
    featured: false,
  },
  {
    id: '5',
    name: 'Loaded Chips',
    description: 'Chips topped with cheese sauce and bacon bits',
    price: 7.99,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=300&fit=crop',
    categorySlug: 'chips',
    categoryId: '2',
    inStock: true,
    featured: true,
    discount: 1.00,
  },
  // Drinks
  {
    id: '6',
    name: 'Soft Drink',
    description: 'Coca-Cola, Sprite, or Fanta',
    price: 2.49,
    image: 'https://images.unsplash.com/photo-1024904250291-958434c77065?w=400&h=300&fit=crop',
    categorySlug: 'drinks',
    categoryId: '3',
    inStock: true,
    featured: false,
  },
  {
    id: '7',
    name: 'Milkshake',
    description: 'Vanilla, Chocolate, or Strawberry',
    price: 4.99,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=300&fit=crop',
    categorySlug: 'drinks',
    categoryId: '3',
    inStock: true,
    featured: false,
  },
  {
    id: '8',
    name: 'Fresh Lemonade',
    description: 'Homemade fresh lemonade with mint',
    price: 3.49,
    image: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=400&h=300&fit=crop',
    categorySlug: 'drinks',
    categoryId: '3',
    inStock: true,
    featured: true,
  },
  // Family Deals
  {
    id: '9',
    name: 'Family Box',
    description: '4 pieces of fish, large chips, 4 drinks',
    price: 34.99,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
    categorySlug: 'family-deals',
    categoryId: '4',
    inStock: true,
    featured: true,
    discount: 5.00,
  },
  {
    id: '10',
    name: 'Kids Meal',
    description: '1 piece of fish, small chips, drink',
    price: 8.99,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    categorySlug: 'family-deals',
    categoryId: '4',
    inStock: true,
    featured: false,
  },
  // Special Offers
  {
    id: '11',
    name: 'Friday Special',
    description: 'Large cod & chips with drink',
    price: 11.99,
    image: 'https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=400&h=300&fit=crop',
    categorySlug: 'special-offers',
    categoryId: '5',
    inStock: true,
    featured: true,
    discount: 2.00,
  },
  {
    id: '12',
    name: 'Combo Deal',
    description: 'Fish, chips, mushy peas, and drink',
    price: 13.99,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    categorySlug: 'special-offers',
    categoryId: '5',
    inStock: true,
    featured: true,
  },
]
